Add `enable_unsafe_legacy_renegotiation` param to work around
```
requests.exceptions.SSLError: HTTPSConnectionPool(host='vpn.mycompany.biz', port=443): Max retries exceeded with url: /global-protect/prelogin.esp (Caused by SSLError(SSLError(1, '[SSL: UNSAFE_LEGACY_RENEGOTIATION_DISABLED] unsafe legacy renegotiation disabled (_ssl.c:997)')))
```